### ISSUE TITLE
'ModelPatcher' object has no attribute 'set_model_attn2_replace' Error for SD 1.5

### ISSUE THREAD

**Issue by taabata** [laksjdjf/IPAdapter-ComfyUI#13]
Hello, thank you for the work you've done, but im facing this error whenever i try to use the workflow you have provided. Any idea why?

im using v1-5-pruned-emaonly.safetensors as the checkpoint by the way

Error occurred when executing IPAdapter:

'ModelPatcher' object has no attribute 'set_model_attn2_replace'

File "/home/mohammad/ComfyUI/execution.py", line 141, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/mohammad/ComfyUI/execution.py", line 75, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/mohammad/ComfyUI/execution.py", line 68, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/mohammad/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 146, in adapter
new_model.set_model_attn2_replace(self.patch_forward(number), "input", id)

**Comment by laksjdjf** [comment]
Is ComfyUI the latest version?

**Comment by taabata** [comment]
nope, it wasnt. Now it works with the updated one. Thank you.
