### ISSUE TITLE
IP-Adapter with fine-grained features (ip-adapter-plus) support

### ISSUE THREAD

**Issue by Ratinod** [laksjdjf/IPAdapter-ComfyUI#14]
Will support be added?
- https://huggingface.co/h94/IP-Adapter/blob/main/models/ip-adapter-plus_sd15.bin
- https://github.com/tencent-ailab/IP-Adapter/commit/73a4246a7463e39973317072a6457053d61038e1

**Comment by laksjdjf** [comment]
It's now supported.
