### ISSUE TITLE
clip vision encode

### ISSUE THREAD

**Issue by cubiq** [laksjdjf/IPAdapter-ComfyUI#20]
hope you don't mind my asking, why aren't you using the clip vision encode node anymore? Every time there's a change in comfy clipvision the IPAdapter node might break (as it happened recently)

**Comment by laksjdjf** [comment]
That's a good question.

There are two reasons why I do not use `CLIPVisionEncode`.
1. `CLIPVisionEncode` does not output `hidden_states`, but `IP-Adapter-plus` requires it. 
2.  `IP-Adapter-plus` needs a black image for the negative side. I think it is inconvenient for users to prepare black image.

Relevant parts of the code:
https://github.com/laksjdjf/IPAdapter-ComfyUI/blob/90e65311f6a03ac52b57a0d2d4aeaab75484c739/ip_adapter.py#L232-L241

**Comment by cubiq** [comment]
that's interesting. thanks for your answer
