### ISSUE TITLE
New IPAdapter doesnt work (from 2023/9/08)

### ISSUE THREAD

**Issue by specblades** [laksjdjf/IPAdapter-ComfyUI#27]
Error with new IPAdapter

<img width="439" alt="image" src="https://github.com/laksjdjf/IPAdapter-ComfyUI/assets/113993746/d1fb43b3-9c30-425b-a850-bf715d8a3fe2">

Note in IPA repo:
<img width="534" alt="image" src="https://github.com/laksjdjf/IPAdapter-ComfyUI/assets/113993746/12261eab-0d3a-4db2-bb73-43b519e99b40">

**Comment by laksjdjf** [comment]
This model  uses CLIP_VISION for SDv15.

**Comment by specblades** [comment]
awwwww rly! Thank you!
