### ISSUE TITLE
IpAdapter  0.0 seconds (IMPORT FAILED)

### ISSUE THREAD

**Issue by playerbrodie** [laksjdjf/IPAdapter-ComfyUI#43]
` 0.0 seconds (IMPORT FAILED): F:\AI\Stable Diff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus`

![image](https://github.com/laksjdjf/IPAdapter-ComfyUI/assets/81574239/f143f42f-8e37-4bbb-9ad5-39b528cace63)

I've tried updating/downgrading/etc opencv. No go.

**Comment by laksjdjf** [comment]
this issues is in https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by playerbrodie** [comment]
oops
