### ISSUE TITLE
can you also support safetensors?

### ISSUE THREAD

**Issue by xiaohu2015** [laksjdjf/IPAdapter-ComfyUI#46]
@laksjdjf hi, thank you very much for developing this plugin. Recently, we conveted the model to  safetensors. I would be very grateful if you could support this.

https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter/ip_adapter.py#L91-L97

**Comment by laksjdjf** [comment]
I already support it by reference to https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/56
Thanks!
